import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import Provider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <head>
        <style>
          {`
            @import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap');
            
            .lato-thin { font-family: "Lato", sans-serif; font-weight: 100; font-style: normal; }
            .lato-light { font-family: "Lato", sans-serif; font-weight: 300; font-style: normal; }
            .lato-regular { font-family: "Lato", sans-serif; font-weight: 400; font-style: normal; }
            .lato-bold { font-family: "Lato", sans-serif; font-weight: 700; font-style: normal; }
            .lato-black { font-family: "Lato", sans-serif; font-weight: 900; font-style: normal; }
            .lato-thin-italic { font-family: "Lato", sans-serif; font-weight: 100; font-style: italic; }
            .lato-light-italic { font-family: "Lato", sans-serif; font-weight: 300; font-style: italic; }
            .lato-regular-italic { font-family: "Lato", sans-serif; font-weight: 400; font-style: italic; }
            .lato-bold-italic { font-family: "Lato", sans-serif; font-weight: 700; font-style: italic; }
            .lato-black-italic { font-family: "Lato", sans-serif; font-weight: 900; font-style: italic; }
          `}
        </style>
      </head>
      <body className="lato-regular antialiased">
        <Provider>
        {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
