"use client";
import React, { useState, useEffect } from 'react';
import { Play, Calendar, CheckSquare, Sparkles, BookOpen, Loader2 } from 'lucide-react';
import Link from 'next/link';
import { useUser } from '@clerk/nextjs';
import axios from 'axios';

interface ActiveCourse {
  courseId: string;
  courseName: string;
  description: string;
  progressPercentage: number;
  totalChapters: number;
  completedChapters: number;
  currentChapterName: string;
  currentChapterId: string;
  nextReview: string;
}

function ContinueLearning() {
  const { user, isLoaded } = useUser();
  const [activeCourses, setActiveCourses] = useState<ActiveCourse[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user) {
      fetchInsights();
    } else {
      setLoading(false);
    }
  }, [user]);

  const fetchInsights = async () => {
    try {
      const res = await axios.get('/api/learning-insights');
      setActiveCourses(res.data.activeCourses || []);
    } catch (e) {
      console.error("Failed to fetch active courses progress:", e);
    } finally {
      setLoading(false);
    }
  };

  if (!isLoaded || loading || !user || activeCourses.length === 0) return null;

  // Most active course goes first
  const primaryCourse = activeCourses[0];
  const secondaryCourses = activeCourses.slice(1);

  return (
    <section className="w-full px-6 md:px-12 lg:px-24 py-12 bg-[#faf8f5]">
      <div className="max-w-6xl mx-auto flex flex-col gap-6">
        <div className="flex items-center gap-3">
          <BookOpen className="w-8 h-8 text-sketch-primary" />
          <h2 className="font-display text-3xl font-bold underline decoration-sketch-orange decoration-4 underline-offset-8">
            Continue Learning
          </h2>
        </div>

        <div className="w-full mt-4">
          {/* Main Active Course Card */}
          <div className="w-full wobbly-border hard-shadow bg-white p-8 relative rotate-[0.5deg]">
            {/* Thumbtack Decoration */}
            <div className="thumbtack absolute -top-3 left-1/2 -translate-x-1/2 z-20"></div>
            
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-8">
              <div className="flex-1 flex flex-col gap-3">
                <span className="font-display text-sm tracking-wider uppercase text-sketch-primary font-bold bg-purple-50 px-3 py-1 wobbly-border border-2 inline-block self-start">
                  Active Learning Path
                </span>
                <h3 className="font-display text-3xl font-bold text-slate-900 leading-tight">
                  {primaryCourse.courseName}
                </h3>
                <p className="font-sans text-xl text-slate-500 line-clamp-2 leading-snug">
                  {primaryCourse.description || "Personalized curriculum generated by Coursa."}
                </p>

                {/* Progress bar */}
                <div className="flex flex-col gap-2 mt-4 max-w-md">
                  <div className="flex justify-between font-sans font-bold text-lg text-slate-700">
                    <span>Overall Progress</span>
                    <span>{primaryCourse.progressPercentage}%</span>
                  </div>
                  <div className="w-full h-4 bg-slate-100 wobbly-border overflow-hidden relative border-2 border-slate-900">
                    <div
                      className="h-full bg-sketch-primary transition-all duration-500"
                      style={{ width: `${primaryCourse.progressPercentage}%` }}
                    />
                  </div>
                  <div className="flex justify-between font-sans text-sm text-slate-400">
                    <span>{primaryCourse.completedChapters} of {primaryCourse.totalChapters} chapters done</span>
                  </div>
                </div>
              </div>

              {/* Status and CTA Section */}
              <div className="w-full md:w-80 flex flex-col gap-4 bg-slate-50/50 p-6 wobbly-border border-dashed border-2">
                <div className="flex items-start gap-3">
                  <Play className="w-6 h-6 text-sketch-primary shrink-0 mt-0.5" />
                  <div className="flex flex-col">
                    <span className="font-display text-sm text-slate-400 uppercase font-bold">Current Lesson</span>
                    <span className="font-sans text-lg text-slate-800 font-bold leading-tight line-clamp-2">
                      {primaryCourse.currentChapterName}
                    </span>
                  </div>
                </div>

                <div className="flex items-start gap-3 border-t border-dashed border-slate-200 pt-3">
                  <Calendar className="w-6 h-6 text-sketch-orange shrink-0 mt-0.5" />
                  <div className="flex flex-col">
                    <span className="font-display text-sm text-slate-400 uppercase font-bold">Next SRS Review</span>
                    <span className="font-sans text-lg text-slate-800 font-bold">
                      {primaryCourse.nextReview}
                    </span>
                  </div>
                </div>

                <Link
                  href={`/course/${primaryCourse.courseId}`}
                  className="w-full mt-2"
                >
                  <button className="w-full bg-sketch-primary text-white font-display text-2xl py-3 wobbly-border hard-shadow-sm hover:translate-x-0.5 hover:translate-y-0.5 hover:shadow-none transition-all flex items-center justify-center gap-2 cursor-pointer">
                    <span>Resume Learning</span>
                    <Play className="w-4 h-4 fill-white" />
                  </button>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default ContinueLearning;
